# Generated by Django 5.0.6 on 2024-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.IntegerField(max_length=200)),
                ('phone', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=150)),
            ],
        ),
    ]
