# Generated by Django 5.0.6 on 2024-06-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_remove_employee_id_employee_working_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working',
            field=models.CharField(max_length=12),
        ),
    ]
